import type { EscapeStage } from '../types';

export const escapeStages: EscapeStage[] = [
  {
    id: 'stage1',
    subject: 'matematica',
    title: 'Módulo de Criptografia',
    narrative: 'O hacker criptografou o servidor com uma senha numérica. Para descriptografar, você precisa resolver a equação que ele deixou como pista.',
    type: 'multiple_choice',
    question: 'Qual é o valor de X na equação: 3x + 15 = 2x + 28?',
    options: ['x = 10', 'x = 13', 'x = 7', 'x = 11'],
    answer: 'x = 13',
    hint: 'Isole o X: 3x - 2x = 28 - 15',
    points: 100,
  },
  {
    id: 'stage2',
    subject: 'portugues',
    title: 'Mensagem Codificada',
    narrative: 'O hacker deixou uma mensagem de ameaça, mas ela está com erros de digitação propositais para confundir o sistema antivírus. Encontre a frase correta.',
    type: 'multiple_choice',
    question: 'Qual alternativa está CORRETA em relação ao uso da vírgula?',
    options: [
      'Eu, fui à escola ontem.',
      'Maria, que é minha amiga, chegou cedo.',
      'O professor falou que, todos devem estudar.',
      'Hoje, eu e, meu irmão fomos juntos.',
    ],
    answer: 'Maria, que é minha amiga, chegou cedo.',
    hint: 'Orações subordinadas adjetivas explicativas são separadas por vírgulas.',
    points: 100,
  },
  {
    id: 'stage3',
    subject: 'logica',
    title: 'Sequência de Acesso',
    narrative: 'O painel de controle está trancado por uma sequência lógica. Você precisa descobrir o próximo número para destravar o firewall.',
    type: 'text_input',
    question: 'Complete a sequência: 2, 6, 12, 20, 30, ___',
    answer: '42',
    hint: 'Observe as diferenças entre os termos: +4, +6, +8, +10…',
    points: 150,
  },
  {
    id: 'stage4',
    subject: 'geral',
    title: 'Banco de Dados Histórico',
    narrative: 'O hacker apagou registros históricos do servidor escolar. Para restaurá-los, você precisa responder à pergunta que protege o backup.',
    type: 'multiple_choice',
    question: 'Em que ano o Brasil proclamou sua Independência de Portugal?',
    options: ['1808', '1822', '1889', '1500'],
    answer: '1822',
    hint: 'D. Pedro I proclamou a independência às margens do Rio Ipiranga.',
    points: 100,
  },
  {
    id: 'stage5',
    subject: 'enigma',
    title: 'O Enigma do Hacker',
    narrative: 'O hacker deixou um enigma final antes de fugir. Resolva-o para recuperar o último fragmento do sistema.',
    type: 'text_input',
    question: '🔒 Enigma: "Tenho cidades, mas nenhuma casa mora lá. Tenho montanhas, mas nenhuma árvore cresce. Tenho água, mas nenhum peixe nada. Tenho estradas, mas nenhum carro as percorre. O que sou eu?"',
    answer: 'mapa',
    hint: 'Pense em algo que representa o mundo, mas não é o mundo.',
    points: 200,
  },
  {
    id: 'stage6',
    subject: 'colaborativo',
    title: 'Protocolo de Restauração Final',
    narrative: '⚡ ATENÇÃO — Este é o desafio final! O sistema exige uma senha de 6 dígitos que só pode ser reconstituída em equipe. Cada aluno do grupo deve olhar para o colega ao lado e compartilhar UM número em voz alta. O resultado é a soma de todos os números dividida pela quantidade de pessoas.',
    type: 'collaborative',
    question: '🤝 DESAFIO COLABORATIVO\n\nPasso 1: Cada aluno do grupo escolhe mentalmente um número de 1 a 10.\nPasso 2: Todos falam seus números ao mesmo tempo em voz alta.\nPasso 3: Some todos os números do grupo.\nPasso 4: Se a soma for par, a senha é "SISTEMA RESTAURADO". Se for ímpar, a senha é "ACESSO LIBERADO".\n\nQual foi o resultado da soma do grupo?',
    options: ['A soma foi PAR → SISTEMA RESTAURADO', 'A soma foi ÍMPAR → ACESSO LIBERADO'],
    answer: 'any',
    hint: 'Este desafio não tem resposta errada — o importante é a colaboração!',
    points: 250,
    requiresPhysical: true,
  },
];
